version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - '8000:8000'
      - '5678:5678'
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DB=todo-api
      - LOG_LEVEL=DEBUG
      - SECRET_KEY=change_me_in_prod
      - PYDEVD_DISABLE_FILE_VALIDATION=1
      - PYTHONPATH=.
      - IN_DOCKER=1
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    command: npm run dev
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
